### ISSUE TITLE
should `getResources` return all resources if no label or ids are provided?

### ISSUE THREAD

**Issue by marlonpp** [jamesplease/redux-resource#177]
Should `[getResources](https://github.com/jmeas/resourceful-redux/blob/master/packages/resourceful-redux/src/utils/get-resources.js#L2)` return all resources if no label or ids are provided?
It would be concise way to get resources, not only if I want a specific label or specific items.

**Comment by jmeas** [comment]
Not a bad suggestion, @marlonpp . This would be straightforward to add in, I think. The only possible downside that I can think of would be protecting against:

`getResources(someUndefinedVar)`

Currently, we could add in a check that would explode if you do this. With this update, all of the resources would be returned, which may be unexpected if you make that mistake.

Without this feature, you can achieve the same thing using:

```js
Object.values(state.books.resources)
```

I'm open to adding this behavior, though, if folks like it. Thoughts @sprjr @tbranyen @vinodkl?

**Comment by jmeas** [comment]
Just chatted with @marlonpp . We decided that we're going to close this issue for now. Once lists are added, we won't recommend that folks use the whole slice anymore, so this feature wouldn't be needed then. We don't want to remove functionality later on, so we're going to hold off on adding this until at least after lists are added to see if we still need it.

For now, `Object.values(state.books.resources);` is the recommended approach

**Comment by tbranyen** [comment]
Is Object.values a standard yet? Last I tried in Chrome it didn't exist.

**Comment by jmeas** [comment]
Yeah, it's in ES2017, and now in Chrome and other browsers.

![image](https://user-images.githubusercontent.com/2322305/29688841-e7d92d38-88d5-11e7-8d6f-80721b7d0f93.png)

Because many users of Redux also use React, and many users of React use Babel, I think there's a good chance folks will be using Babel and can transpile this if they need to.

This `Object.values()` recommendation is temporary until we get lists implemented (which hopefully shouldn't be too far away...)

**Comment by sprjr** [comment]
Object.values is a suggestion though, I mean really you can use lodash or map it yourself - we don't care about that part.

**Comment by jmeas** [comment]
I'll consider this for v3.

**Comment by sprjr** [comment]
Would like to revisit this issue as it's causing an issue in some of my application usage. I spoke with @marlonpp and it sounds like the use case we're trying to solve here is for the API:

```
const allBooks = getResource(state.books);
```

in which you don't have to pass a filter function like `Boolean` or anything else to just 'get all resources'. I think that's a valuable thing to have or consider for sure. Here is the issue I am running into:

```
const favoriteBooks = getResources(state.books, _.get(state.books, 'requests.favoriteBooks.ids'))
```

In this case, because I did _not_ opt for the 3rd argument in `_.get` to provide a default value, what I'm calling in some cases is:

```
const favoriteBooks = getResources(state.books, undefined)
```

This is causing _all_ resources to be returned, which I think results in a worse state because the developer was not intending to get all resources, they may have just been intending to get a few of them, and were otherwise unaware of the "array" being "undefined". I think this is likely to occur more often when using non-typed systems, and SILO backends where you might have been relying on server data to do look ups in the store, e.g. `getResources(state.books, user.favoriteBooks)` from an API that allows `[1,2,3]`, `[]`, and `undefined` as valid data.

@jamesplease what do you think about breaking this again?

**Comment by jamesplease** [comment]
> @jamesplease what do you think about breaking this again?

I'm a little hesitant just due to the API thrash, but I think it is worthwhile to make this change.

I'm currently thinking of a `getResources('books', true)` shorthand, which would return all of the resources. `getResources('books', undefined)` would return nothing.

@marlonpp / @sprjr what do you two think?

**Comment by jamesplease** [comment]
Gonna close this as revisit. I don't plan to introduce a breaking change atm, but if I do, then I'll roll this into it.

To ensure that folks don't get tripped up, we can:

1. add a deprecation warning in a 3.x release for the current behavior
2. at the same time, add the new API into 3.x
3. remove the problematic behavior in 4.x
