### ISSUE TITLE
 v3 beta: DELETE_RESOURCES_SUCCEEDED doesn't remove entry in "resources" object in store

### ISSUE THREAD

**Issue by au-re** [jamesplease/redux-resource#376]
redux-resource: 3.0.0-beta4
redux-resource-plugins: 3.0.0-beta4

Maybe I'm doing something wrong but when I dispatch:
```
    dispatch({
      type: actionTypes.DELETE_RESOURCES_SUCCEEDED,
      resourceType: "cat",
      request: "deleteCat",
      resources: ["123"],
    });
```
it sets the resource object in the store to:

```
cats: {
  resources: {
    "123": null,
  }
}
```
acording to [the wiki](https://redux-resource.js.org/docs/guides/deleting-resources)

> When an action of type DELETE_RESOURCES_SUCCEEDED is dispatched, any resources included in the action will be removed from the resources array of your state tree. 

The problem is that calling `getResources` after a deletion fails with a `resource is null` error.
In [get-resources.js](https://github.com/jamesplease/redux-resource/blob/master/packages/redux-resource/src/utils/get-resources.js) there is no check to make sure the resource is an object.

**Comment by jamesplease** [comment]
Thanks for the report! I’ll fix this soon. I am sick with the flu atm so it may not be today 🤒

**Comment by jamesplease** [comment]
@au-re can you post the arguments you’re passing to `getResources`?

**Comment by au-re** [comment]
Thanks for the quick reply!
I'm calling `getResources` in mapStateToProps and passing the state slice 

```
const mapStateToProps = (state, props) => ({
  cats: getResources(state.cats)
});
```

I setup the reducer like so:

```
import { resourceReducer } from "redux-resource";
import { httpStatusCodes, reset } from "redux-resource-plugins";

export default {
  cats: resourceReducer("cats", { plugins: [httpStatusCodes, reset] }),
};
```

And add it to the store:

```
import { applyMiddleware, combineReducers, createStore } from "redux";
import thunk from "redux-thunk";

import reducers from "./reducers";

const middlewares = [thunk];

const store = createStore(
  combineReducers({
    ...reducers,
  }),
  applyMiddleware(...middlewares),
);
```

**Comment by jamesplease** [comment]
Thanks for the details @au-re !

It turns out that this issue also affects v2. I am thinking about the best solution there. This is a consequence of the addition of the new filter function signature in `getResources`; I didn't consider this as a consequence, and so far we haven't run into this as Netflix (pretty surprising to me tbqh).

Also, I noticed that you referenced the v2 documentation (redux-resource.js.org) when you reported this issue. I do not encourage you to read the v2 docs if you are using v3. That didn't lead to this problem, but v3 has many improvements over v2, so you should definitely use the [v3 docs](https://jamesplease.github.io/redux-resource-3.0-docs/) instead if you intend to use the beta!

Lastly, I PR'd a solution over in #377 :v: I will release it as beta5 shortly :+1:

**Comment by jamesplease** [comment]
A fix has been released as beta5. Let me know if you still run into the issue. Thanks for the report @au-re ! I will open another issue to track fixing this in v2.
