### ISSUE TITLE
Possibility to use dedupe on redux-resource-xhr?

### ISSUE THREAD

**Issue by svobik7** [jamesplease/redux-resource#430]
Hi there, first of all thank you for great library.

I am using `redux-resource` with `redux-resource-xhr` and trying to solve how to make it work with request deduplication.

I found you published `fetch-dedupe` library which is great but I think it is not "applicable" to `redux-resource-xhr`.

Is this feature on your ROADMAP or do you have any idea how to solve this?

**Comment by jamesplease** [comment]
@svobik7 sorry for the late reply! At the moment you would need to write your own implementation of `redux-resource-xhr` to take advantage of `fetch-dedupe`. 

I started this over in https://github.com/jamesplease/redux-resource/pull/412/files , which uses the native `fetch` API rather than `fetch-dedupe`, but given the API similarities between the two, it shouldn't be hard to adapt it.

Hope that helps!
